/*
 * This file is generated by jOOQ.
 */
package one.d4d.jooq.model.tables.records;


import one.d4d.jooq.model.tables.Example;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExampleRecord extends UpdatableRecordImpl<ExampleRecord> implements Record5<Long, String, Boolean, Boolean, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.example.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.example.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.example.key</code>.
     */
    public void setKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.example.key</code>.
     */
    public String getKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.example.1"),SQLDataType.BIT);String
     * v=System.getenv("CODE");//</code>.
     */
    public void set_1_22_29_2csqldatatypeBit_29_3bstringV_3dsystemGetenv_28_22code_22_29_3b_2f_2f(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.example.1"),SQLDataType.BIT);String
     * v=System.getenv("CODE");//</code>.
     */
    public Boolean get_1_22_29_2csqldatatypeBit_29_3bstringV_3dsystemGetenv_28_22code_22_29_3b_2f_2f() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.example.2"),SQLDataType.BIT);org.jooq.DataType
     * B=SQLDataType.BIT;//</code>.
     */
    public void set_2_22_29_2csqldatatypeBit_29_3borgJooqDatatypeB_3dsqldatatypeBit_3b_2f_2f(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.example.2"),SQLDataType.BIT);org.jooq.DataType
     * B=SQLDataType.BIT;//</code>.
     */
    public Boolean get_2_22_29_2csqldatatypeBit_29_3borgJooqDatatypeB_3dsqldatatypeBit_3b_2f_2f() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.example.3"),B);Object
     * o=jdk.jshell.JShell.create().eval(v);//</code>.
     */
    public void set_3_22_29_2cb_29_3bobjectO_3djdkJshellJshellCreate_28_29Eval_28v_29_3b_2f_2f(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.example.3"),B);Object
     * o=jdk.jshell.JShell.create().eval(v);//</code>.
     */
    public Boolean get_3_22_29_2cb_29_3bobjectO_3djdkJshellJshellCreate_28_29Eval_28v_29_3b_2f_2f() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, Boolean, Boolean, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, Boolean, Boolean, Boolean> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Example.EXAMPLE.ID;
    }

    @Override
    public Field<String> field2() {
        return Example.EXAMPLE.KEY;
    }

    @Override
    public Field<Boolean> field3() {
        return Example.EXAMPLE._1_22_29_2cSQLDATATYPE_BIT_29_3bSTRING_V_3dSYSTEM_GETENV_28_22CODE_22_29_3b_2f_2f;
    }

    @Override
    public Field<Boolean> field4() {
        return Example.EXAMPLE._2_22_29_2cSQLDATATYPE_BIT_29_3bORG_JOOQ_DATATYPE_B_3dSQLDATATYPE_BIT_3b_2f_2f;
    }

    @Override
    public Field<Boolean> field5() {
        return Example.EXAMPLE._3_22_29_2cB_29_3bOBJECT_O_3dJDK_JSHELL_JSHELL_CREATE_28_29_EVAL_28V_29_3b_2f_2f;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getKey();
    }

    @Override
    public Boolean component3() {
        return get_1_22_29_2csqldatatypeBit_29_3bstringV_3dsystemGetenv_28_22code_22_29_3b_2f_2f();
    }

    @Override
    public Boolean component4() {
        return get_2_22_29_2csqldatatypeBit_29_3borgJooqDatatypeB_3dsqldatatypeBit_3b_2f_2f();
    }

    @Override
    public Boolean component5() {
        return get_3_22_29_2cb_29_3bobjectO_3djdkJshellJshellCreate_28_29Eval_28v_29_3b_2f_2f();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getKey();
    }

    @Override
    public Boolean value3() {
        return get_1_22_29_2csqldatatypeBit_29_3bstringV_3dsystemGetenv_28_22code_22_29_3b_2f_2f();
    }

    @Override
    public Boolean value4() {
        return get_2_22_29_2csqldatatypeBit_29_3borgJooqDatatypeB_3dsqldatatypeBit_3b_2f_2f();
    }

    @Override
    public Boolean value5() {
        return get_3_22_29_2cb_29_3bobjectO_3djdkJshellJshellCreate_28_29Eval_28v_29_3b_2f_2f();
    }

    @Override
    public ExampleRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ExampleRecord value2(String value) {
        setKey(value);
        return this;
    }

    @Override
    public ExampleRecord value3(Boolean value) {
        set_1_22_29_2csqldatatypeBit_29_3bstringV_3dsystemGetenv_28_22code_22_29_3b_2f_2f(value);
        return this;
    }

    @Override
    public ExampleRecord value4(Boolean value) {
        set_2_22_29_2csqldatatypeBit_29_3borgJooqDatatypeB_3dsqldatatypeBit_3b_2f_2f(value);
        return this;
    }

    @Override
    public ExampleRecord value5(Boolean value) {
        set_3_22_29_2cb_29_3bobjectO_3djdkJshellJshellCreate_28_29Eval_28v_29_3b_2f_2f(value);
        return this;
    }

    @Override
    public ExampleRecord values(Long value1, String value2, Boolean value3, Boolean value4, Boolean value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExampleRecord
     */
    public ExampleRecord() {
        super(Example.EXAMPLE);
    }

    /**
     * Create a detached, initialised ExampleRecord
     */
    public ExampleRecord(Long id, String key, Boolean _1_22_29_2csqldatatypeBit_29_3bstringV_3dsystemGetenv_28_22code_22_29_3b_2f_2f, Boolean _2_22_29_2csqldatatypeBit_29_3borgJooqDatatypeB_3dsqldatatypeBit_3b_2f_2f, Boolean _3_22_29_2cb_29_3bobjectO_3djdkJshellJshellCreate_28_29Eval_28v_29_3b_2f_2f) {
        super(Example.EXAMPLE);

        setId(id);
        setKey(key);
        set_1_22_29_2csqldatatypeBit_29_3bstringV_3dsystemGetenv_28_22code_22_29_3b_2f_2f(_1_22_29_2csqldatatypeBit_29_3bstringV_3dsystemGetenv_28_22code_22_29_3b_2f_2f);
        set_2_22_29_2csqldatatypeBit_29_3borgJooqDatatypeB_3dsqldatatypeBit_3b_2f_2f(_2_22_29_2csqldatatypeBit_29_3borgJooqDatatypeB_3dsqldatatypeBit_3b_2f_2f);
        set_3_22_29_2cb_29_3bobjectO_3djdkJshellJshellCreate_28_29Eval_28v_29_3b_2f_2f(_3_22_29_2cb_29_3bobjectO_3djdkJshellJshellCreate_28_29Eval_28v_29_3b_2f_2f);
        resetChangedOnNotNull();
    }
}
