/*
 * This file is generated by jOOQ.
 */
package one.d4d.jooq.model;


import one.d4d.jooq.model.tables.Example;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.example</code>.
     */
    public static final Example EXAMPLE = Example.EXAMPLE;
}
